[package]
name = "common"
description = "TODO: write description"
version = "0.1.0"
edition = "2021"
authors = ["Jiseok CHOI <jiseok.dev@gmail.com>"]

[dependencies]
gluesql = "0.10"
async-trait = "0.1"
thiserror = "1"
