[package]
name = "data-collector"
description = "TODO: write description"
version = "0.1.0"
edition = "2021"
authors = ["Jiseok CHOI <jiseok.dev@gmail.com>"]

[dependencies]
gluesql = { version = "0.10.2" }
thiserror = "1"
